#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x7c7e1083, __VMLINUX_SYMBOL_STR(module_layout) },
	{        0, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0x6de7e05e, __VMLINUX_SYMBOL_STR(fs_bio_set) },
	{ 0x9aee5364, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0xc897c382, __VMLINUX_SYMBOL_STR(sg_init_table) },
	{ 0x91ce249a, __VMLINUX_SYMBOL_STR(alloc_disk) },
	{ 0x18599355, __VMLINUX_SYMBOL_STR(blk_cleanup_queue) },
	{ 0x4b0f5204, __VMLINUX_SYMBOL_STR(alloc_disk_node) },
	{ 0xda3e43d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xb43a926b, __VMLINUX_SYMBOL_STR(backport_dependency_symbol) },
	{ 0xd6ee688f, __VMLINUX_SYMBOL_STR(vmalloc) },
	{ 0x784213a6, __VMLINUX_SYMBOL_STR(pv_lock_ops) },
	{ 0xb6b46a7c, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x1c0b531a, __VMLINUX_SYMBOL_STR(blk_queue_max_hw_sectors) },
	{ 0xbd100793, __VMLINUX_SYMBOL_STR(cpu_online_mask) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0x32bded08, __VMLINUX_SYMBOL_STR(__tracepoint_block_bio_remap) },
	{ 0x866c7d0d, __VMLINUX_SYMBOL_STR(ib_destroy_qp) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{        0, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r9) },
	{ 0xf087137d, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{        0, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rcx) },
	{ 0x3fec048f, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0x88cbc1eb, __VMLINUX_SYMBOL_STR(blk_mq_end_io) },
	{ 0x4e7fc06f, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x54efb5d6, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x40c7247c, __VMLINUX_SYMBOL_STR(si_meminfo) },
	{ 0x2e55d444, __VMLINUX_SYMBOL_STR(kthread_create_on_node) },
	{ 0xee327586, __VMLINUX_SYMBOL_STR(lookup_bdev) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x524a8f67, __VMLINUX_SYMBOL_STR(rdma_connect) },
	{ 0xd2afdaad, __VMLINUX_SYMBOL_STR(blk_mq_init_queue) },
	{ 0xf432dd3d, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xd3af89f4, __VMLINUX_SYMBOL_STR(ib_alloc_pd) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xc49a6d2e, __VMLINUX_SYMBOL_STR(blk_alloc_queue) },
	{ 0x8f64aa4, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x2e03b63, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x6f956c0e, __VMLINUX_SYMBOL_STR(ib_get_dma_mr) },
	{ 0xedc2c661, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x20c55ae0, __VMLINUX_SYMBOL_STR(sscanf) },
	{ 0x811783a9, __VMLINUX_SYMBOL_STR(kthread_stop) },
	{ 0x106aa373, __VMLINUX_SYMBOL_STR(del_gendisk) },
	{ 0x7c1372e8, __VMLINUX_SYMBOL_STR(panic) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0x91d09ae8, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xeb9d1ba0, __VMLINUX_SYMBOL_STR(config_group_init_type_name) },
	{ 0x71a50dbc, __VMLINUX_SYMBOL_STR(register_blkdev) },
	{ 0x124924e7, __VMLINUX_SYMBOL_STR(generic_make_request) },
	{ 0xebf82fd0, __VMLINUX_SYMBOL_STR(configfs_register_subsystem) },
	{ 0xef78a244, __VMLINUX_SYMBOL_STR(rdma_create_id) },
	{ 0xd777e67a, __VMLINUX_SYMBOL_STR(bio_endio) },
	{ 0xc3cf9695, __VMLINUX_SYMBOL_STR(ib_destroy_cq) },
	{ 0x5d5b5a16, __VMLINUX_SYMBOL_STR(radix_tree_delete) },
	{ 0x9f46ced8, __VMLINUX_SYMBOL_STR(__sw_hweight64) },
	{ 0x61651be, __VMLINUX_SYMBOL_STR(strcat) },
	{ 0xb5a459dc, __VMLINUX_SYMBOL_STR(unregister_blkdev) },
	{ 0xe3deb77, __VMLINUX_SYMBOL_STR(rdma_create_qp) },
	{ 0x40a9b349, __VMLINUX_SYMBOL_STR(vzalloc) },
	{ 0xebdbe48c, __VMLINUX_SYMBOL_STR(radix_tree_gang_lookup) },
	{ 0x239cd995, __VMLINUX_SYMBOL_STR(rdma_resolve_route) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0x454075ca, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0x37a218c2, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_node_trace) },
	{ 0xe7b6c68, __VMLINUX_SYMBOL_STR(blkdev_put) },
	{ 0xc7177020, __VMLINUX_SYMBOL_STR(blk_queue_make_request) },
	{ 0x8662dd7a, __VMLINUX_SYMBOL_STR(blk_queue_physical_block_size) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xa202a8e5, __VMLINUX_SYMBOL_STR(kmalloc_order_trace) },
	{ 0xaccabc6a, __VMLINUX_SYMBOL_STR(in4_pton) },
	{ 0xbf267ed1, __VMLINUX_SYMBOL_STR(put_disk) },
	{ 0x3d9ee9f0, __VMLINUX_SYMBOL_STR(clear_page) },
	{ 0x43261dca, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{        0, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rax) },
	{ 0xe6e017af, __VMLINUX_SYMBOL_STR(blk_rq_map_sg) },
	{ 0x237e99b6, __VMLINUX_SYMBOL_STR(wake_up_process) },
	{ 0x1d711591, __VMLINUX_SYMBOL_STR(configfs_unregister_subsystem) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xd9d10a1c, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x61fb248a, __VMLINUX_SYMBOL_STR(node_states) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x54b5a642, __VMLINUX_SYMBOL_STR(bio_clone_bioset) },
	{ 0x9327f5ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x6f8c7d64, __VMLINUX_SYMBOL_STR(ib_dereg_mr) },
	{ 0xcf21d241, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xb3f7646e, __VMLINUX_SYMBOL_STR(kthread_should_stop) },
	{ 0x34f22f94, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0xf86e6216, __VMLINUX_SYMBOL_STR(bio_alloc_pages) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xcb9e05b9, __VMLINUX_SYMBOL_STR(add_disk) },
	{ 0x9754ec10, __VMLINUX_SYMBOL_STR(radix_tree_preload) },
	{ 0xd3719d59, __VMLINUX_SYMBOL_STR(paravirt_ticketlocks_enabled) },
	{ 0xbb589f8d, __VMLINUX_SYMBOL_STR(set_user_nice) },
	{ 0xa72a0f5b, __VMLINUX_SYMBOL_STR(nr_online_nodes) },
	{ 0xfdd91ea7, __VMLINUX_SYMBOL_STR(rdma_resolve_addr) },
	{ 0xb352177e, __VMLINUX_SYMBOL_STR(find_first_bit) },
	{ 0xfa66f77c, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x870bf928, __VMLINUX_SYMBOL_STR(radix_tree_lookup) },
	{ 0x4cbbd171, __VMLINUX_SYMBOL_STR(__bitmap_weight) },
	{ 0x62f96f1b, __VMLINUX_SYMBOL_STR(ib_create_cq) },
	{ 0x4b06d2e7, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x69e08e9, __VMLINUX_SYMBOL_STR(bdget) },
	{ 0xd15e59b3, __VMLINUX_SYMBOL_STR(blkdev_get) },
	{ 0xc6127506, __VMLINUX_SYMBOL_STR(blk_queue_logical_block_size) },
	{ 0xf202c5cb, __VMLINUX_SYMBOL_STR(radix_tree_insert) },
	{ 0x3c7636ea, __VMLINUX_SYMBOL_STR(config_group_init) },
	{ 0x8234d193, __VMLINUX_SYMBOL_STR(blk_mq_map_queue) },
	{ 0xa00fdd49, __VMLINUX_SYMBOL_STR(bdput) },
	{ 0xb2eb7b1c, __VMLINUX_SYMBOL_STR(dma_ops) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=mlx_compat,ib_core,rdma_cm,configfs";


MODULE_INFO(srcversion, "08B767FCA34602B186405E4");
